# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-23 21:34
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_auto_20161224_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=datetime.datetime(2016, 12, 23, 21, 34, 19, 776523, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=datetime.datetime(2016, 12, 23, 21, 34, 27, 485273, tzinfo=utc), max_length=15, validators=[django.core.validators.RegexValidator(message="Phone No. must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='u', max_length=255, unique=True),
        ),
    ]
